name: Run MyApp

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # اجرای کد هر ساعت

jobs:
  run-myapp:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # به‌روزرسانی به v3

    - name: Set up Python
      uses: actions/setup-python@v4  # به‌روزرسانی به v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas mplfinance numpy

    - name: Run MyApp
      run: |
        python main.py
